"""admin-user

Revision ID: 6dc404604ecd
Revises: e5f7887333c3
Create Date: 2025-12-27 13:42:48.321740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dc404604ecd"
down_revision: Union[str, Sequence[str], None] = "e5f7887333c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO \"user\" (user_name, password, role_id) VALUES ('adminadmin','adminadmin', 1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM \"user\" WHERE user_name='adminadmin'")
    # ### end Alembic commands ###
