"""roles

Revision ID: e5f7887333c3
Revises: fc7ebe108edf
Create Date: 2025-12-26 20:10:15.689045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f7887333c3'
down_revision: Union[str, Sequence[str], None] = 'fc7ebe108edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "INSERT INTO roles (role_name) VALUES ('администратор'), ('пользователь')"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM roles WHERE role_name IN ('администратор', 'пользователь')"
    )
    # ### end Alembic commands ###
